on: [push, pull_request]
name: CI
jobs:
  CI:
    name: CI (${{ matrix.version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - name: Install
        # TODO remove the --ignore-engines flag when node 14 support is dropped
        run: yarn install --ignore-engines
      - name: Run tests
        run: yarn test
      - name: Run linting
        run: yarn lint
      - name: Build packages
        run: yarn build
