name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/workflows/markdown_link_checker_config.json'
